#!/bin/bash
# menu/menu - menu utama (router). Isi tiap menu ada di file terpisah:
#   vmess.sh  vless.sh  trojan.sh  utility.sh
. /usr/local/lib/xm/lib.sh
L=/usr/local/lib/xm

run_mod(){ # nama-file
  if [[ -f $L/$1 ]]; then
    bash "$L/$1"
  else
    err "Modul $1 belum terpasang. Jalankan: xm-update"; pause
  fi
}

while true; do
  header "XRAY MANAGER  |  $DOMAIN"
  echo " 1) VMess    (buat & kelola akun)"
  echo " 2) VLESS    (buat & kelola akun)"
  echo " 3) Trojan   (buat & kelola akun)"
  echo " 4) Utility  (pengaturan lainnya)"
  echo " 0) Keluar"
  line; read -rp "Pilih: " c
  case $c in
    1) run_mod vmess.sh ;;
    2) run_mod vless.sh ;;
    3) run_mod trojan.sh ;;
    4) run_mod utility.sh ;;
    0) clear; exit 0 ;;
  esac
done
